export const ONSITE_ROOM_JOIN_REQUEST = "ONSITE_ROOM_JOIN_REQUEST";
export const ONSITE_ROOM_JOIN_ERROR = "ONSITE_ROOM_JOIN_ERROR";
export const ONSITE_ROOM_JOIN_SUCCESS = "ONSITE_ROOM_JOIN_SUCCESS";
export const ONSITE_ROOM_LEAVE_REQUEST = "ONSITE_ROOM_LEAVE_REQUEST";
export const ONSITE_ROOM_LEAVE_ERROR = "ONSITE_ROOM_LEAVE_ERROR";
export const ONSITE_ROOM_LEAVE_SUCCESS = "ONSITE_ROOM_LEAVE_SUCCESS";
export const ONSITE_ROOM_UPDATE_ATTENDEE_COUNTER = "ONSITE_ROOM_UPDATE_ATTENDEE_COUNTER";
