version: 2.1
orbs:
    architect: giantswarm/architect@0.17.0

defaults: &defaults
    working_directory: ~/confetti-frontend
    docker:
        - image: circleci/node:12-buster

job_filters: &job_filters
    filters:
        tags:
            only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
        branches:
            only: /.*/

whitelist: &whitelist
    paths:
        - node_modules/*
        - tsconfig.tsbuildinfo

image_name: &image_name quay.io/giantswarm/confetti-frontend

workflows:
    version: 2

    build:
        jobs:
            - checkout:
                  <<: *job_filters
            - test:
                  requires:
                      - checkout
                  <<: *job_filters
            - lint:
                  requires:
                      - checkout
                  <<: *job_filters
            - format:
                  requires:
                      - checkout
                  <<: *job_filters
            - typecheck:
                  requires:
                      - checkout
                  <<: *job_filters
            - build:
                  requires:
                      - checkout
                  <<: *job_filters

            - push-to-quay:
                  name: push-confetti-frontend-to-quay
                  context: architect
                  requires:
                      - test
                      - lint
                      - format
                      - typecheck
                      - build
                  # Needed to trigger job also on git tag.
                  filters:
                      tags:
                          only: /^v.*/

            - architect/push-to-app-catalog:
                  name: push-confetti-frontend-to-operations-platform-app-catalog
                  context: architect
                  app_catalog: "giantswarm-operations-platform-catalog"
                  app_catalog_test: "giantswarm-operations-platform-test-catalog"
                  chart: "confetti-frontend"
                  requires:
                      - push-confetti-frontend-to-quay
                  # Needed to trigger job also on git tag.
                  filters:
                      tags:
                          only: /^v.*/

jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-npm-deps-{{ checksum "yarn.lock" }}
                      - v1-npm-deps-
            - run:
                  name: Print version information
                  command: |
                      node --version
                      yarn --version
            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile
            - save_cache:
                  paths:
                      - out/*
                      - node_modules
                      - tsconfig.tsbuildinfo
                  key: v1-npm-deps-{{ checksum "yarn.lock" }}
            - persist_to_workspace:
                  root: ~/confetti-frontend
                  <<: *whitelist
    typecheck:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/confetti-frontend
            - run:
                  name: Typecheck code using the TypeScript compiler
                  command: yarn run typecheck
    lint:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/confetti-frontend
            - run:
                  name: Lint code using ESlint
                  command: yarn run lint
    format:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/confetti-frontend
            - run:
                  name: Validate code formatting using Prettier
                  command: yarn run format:validate
    test:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/confetti-frontend
            - run:
                  name: Run tests
                  command: yarn run test
    build:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/confetti-frontend
            - run:
                  name: Build web application
                  command: yarn run build
            - persist_to_workspace:
                  root: ~/confetti-frontend
                  <<: *whitelist
    push-to-quay:
        executor: "architect"
        resource_class: "small"
        steps:
            - checkout
            - setup_remote_docker:
                  version: 19.03.13
            - attach_workspace:
                  at: .
            - push-to-docker:
                  context: architect
                  image: *image_name
                  tag-latest-branch: "master"
                  password_envar: "QUAY_USERNAME"
                  username_envar: "QUAY_PASSWORD"
