version: 2.1
orbs:
  architect: giantswarm/architect@0.10.0

defaults: &defaults
  working_directory: ~/confetti-frontend
  docker:
    - image: circleci/node:12-buster

job_filters: &job_filters
  filters:
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
    branches:
      only: /.*/

whitelist: &whitelist
  paths:
    - node_modules/*

workflows:
  version: 2

  build:
    jobs:
      - checkout:
          <<: *job_filters
      - test:
          requires:
            - checkout
          <<: *job_filters
      - lint:
          requires:
            - checkout
          <<: *job_filters
      - format:
          requires:
            - checkout
          <<: *job_filters
      - typecheck:
          requires:
            - checkout
          <<: *job_filters
      - build:
          requires:
            - checkout
          <<: *job_filters

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-npm-deps-{{ checksum "yarn.lock" }}
          - v1-npm-deps-

      - run:
          name: Print version information
          command: |
            node --version
            yarn --version

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/confetti-frontend
          <<: *whitelist

  typecheck:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: ~/confetti-frontend

      - run:
          name: Typecheck code using the TypeScript compiler
          command: yarn run typecheck

  lint:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: ~/confetti-frontend

      - run:
          name: Lint code using ESlint
          command: yarn run lint

  format:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: ~/confetti-frontend

      - run:
          name: Validate code formatting using Prettier
          command: yarn run format:validate

  test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: ~/confetti-frontend

      - run:
          name: Run tests
          command: yarn run test

  build:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: ~/confetti-frontend

      - run:
          name: Build web application
          command: yarn run build

      - persist_to_workspace:
          root: ~/confetti-frontend
          <<: *whitelist
