kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - port: 3000
      targetPort: http
  selector:
    app: {{ .Values.name }}
